### ISSUE TITLE
More maintainers needed

### ISSUE THREAD

**Issue by danrs** [danrs/xwing-data2#646]
@guidokessels we need more people with merge rights on this repo, and you're the only one who can grant them.

@Ampmann @doweaver @J1mBob have been major contributors lately and so I'm tagging them in this discussion.

Whoever is given merge rights should understand how to run tests locally and how to update the tests/schema as necessary when new waves come out. They should also be able to raise PRs for multiple files at once (single file PRs via the web interface are easy to raise but can lead to messy history and are a pain for merging)

**Comment by danrs** [comment]
Paging @guidokessels

**Comment by danrs** [comment]
Guido appears to be absent, so we intend to fork and migrate this project to a github org. I will update here once this is done, ETA 1-2 weeks

**Comment by guidokessels** [comment]
@danrs My apologies for the very slow response.. I don't check this repo very often anymore. Thank you for keeping everything updated all this time! 

I am more than happy to transfer the entire repo to you so you have complete control over it and can add as many collaborators as you want. Let me know if that works for you.

**Comment by danrs** [comment]
@guidokessels that would be excellent. I plan to migrate this to an org at some stage but if you upgrade me to complete control that will make things easier

**Comment by guidokessels** [comment]
I tried to initiate the transfer but I get an error saying `danrs/xwing-data2` already exists. If I read [this page](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#:~:text=The%20target%20account%20must%20not%20have%20a%20repository%20with%20the%20same%20name%2C%20or%20a%20fork%20in%20the%20same%20network.) correctly it looks like you might have to remove/rename your fork.

**Comment by danrs** [comment]
Thanks for the heads up - I have deleted it

**Comment by guidokessels** [comment]
Thanks. You should now have received a request to accept the transfer of the repo.

**Comment by guidokessels** [comment]
Looks like it worked 🎉 Thanks again for keeping this project running all this time! Good luck with it :)

**Comment by danrs** [comment]
Repo has been transferred and collaborators added. Closing this issue as resolved

I'm a bit disappointed with the non-organisation options for github repo access, but for now we will stick with the "owner and collaborators" model.
